export const types = {
    login: "[Auth] Login",
    logout: "[Auth] Logout",
  
    uiSetError: "[UI] Set Error",
    uiRemoveError: "[UI] Remove Error",
    uiStartLoading: "[UI] Start loading",
    uiFinishLoading: "[UI] Finish loading",

    movieAdd: "[MOVIE] New movie",
    movieLater: "[MOVIE] Watch later movie",
    movieActive: "[MOVIE] Active movie",
    movieLoad: "[MOVIE] Load movie",
    movieUpdate: "[MOVIE] Update movie",
    movieDelete: "[MOVIE] Delete movie",
    movieFile: "[MOVIE] File movie",
    movieLogoutCleaning: "[MOVIE] Cleaning movie",
    movieKeep : "[MOVIE] See later",
    movieTop: "[MOVIE] Top movie",
    movieSearch: "[MOVIE] Search movie",
    movieTrailer: "[MOVIE] Trailer",
    moviePopular: "[MOVIE] Popular",
    movieNotPopular: "[MOVIE] Not popular",
    movieValueSearch: "[MOVIE] Value search",
  };